config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}
  devise_for :users, controllers: { registrations: "registrations" }
  
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  
  resources :users do
  	collection do
  	  get 'compose'
      get 'compose_email'
    end 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  def after_sign_in_path_for(resource)
    users_path
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController <Devise::RegistrationsController
  protected

  def after_update_path_for(resource)
    users_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all.where("id != ?", current_user.id).order('created_at DESC')    
  end

  def show
    @user = User.find(params[:id])
  end
 
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, :alert => "User Successfully Deleted."
  end

  def compose
    @users = User.all.where("id != ?", current_user.id).order('created_at DESC')
  end

  def compose_email
    @user_emails = params[:useremail]
    @user_emails.each do |email|
      UserMailer.send_email_users(email, params[:subject], params[:body]).deliver_now
    end
    redirect_to users_path, :notice => "User Emails Successfully Delivered."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def user_name(user)
  	return "#{user.first_name} #{user.last_name}"
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <h2>User Management</h2>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %> 
        <li><%= link_to 'Edit account', edit_user_registration_path %></li>
        <li class="dropdown"> 
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= user_name(current_user) %><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Compose Email', compose_users_path %></li>
            <li class="divider"></li>
            <li><li><%= link_to 'Sign out', destroy_user_session_path, :method => 'delete' %></li></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to 'Sign in', new_user_session_path %></li>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "User Management" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "User Management" %>">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <div id="main-container" class="container">
      <div class="row">
        <div class="col-xs-12">
          <% flash.each do |name, msg| %>
            <% if msg.is_a?(String) %>
              <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <%= content_tag :div, msg, :id => "flash_#{name}" %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="row">
        <% if user_signed_in? %>
          <div class="col-xs-3">
            <h3>User Management</h3>
          </div>
          <div class="col-xs-9">
            <%= yield %>
          </div>
        <% else %>
          <div class="col-xs-12">
            <%= yield %>
          </div>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/users/compose.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li><%= link_to 'List Users', users_path %></li>
  <li class="active"><%= link_to 'Compose Email', compose_users_path %></li>
</ul>

<h1>Compose Email</h1>

<%= form_tag(compose_email_users_path, :method => 'get', :multipart => true, class: "form-horizontal") do %>
  <div class="form-group">
    <label class="col-sm-2 control-label">User Email's</label>
    <div class="col-sm-10">
      <%= select_tag 'useremail[]', options_for_select(@users.map { |u| [u.email]}), multiple: true, id: "compose_email" %></p>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Subject</label>
    <div class="col-sm-10">
      <!-- <input type="text" name="text" class="form-control" placeholder="Text Input" /> -->
      <%= text_field_tag :subject, '', class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Body</label>
    <div class="col-sm-10">
      <!-- <input type="text" name="text" class="form-control" placeholder="Text Input" /> -->
      <%= text_area_tag :body, '', rows: 10, cols: 25, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Submit</button>
    </div>
  </div>
<% end %>

<script type="text/javascript">
  $(document).ready(function() {
    $('#compose_email').multiselect({
      includeSelectAllOption: true,
      enableFiltering: true
    });
  });
</script>

app/views/users/index.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li class="active"><%= link_to 'List Users', users_path %></li>
  <li><%= link_to 'Compose Email', compose_users_path %></li>
</ul>

<h1>Listing Users</h1>

<table class="table">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to "Show", user, class: 'btn btn-primary btn-xs' %></td>
        <td><%#= link_to "Edit", edit_user_registration_path, class: 'btn btn-info btn-xs' %></td>
        <td><%= link_to "Destroy", user_path(user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First Name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Back', users_path %>